markdown: kramdown
kramdown:
  parse_block_html: true
search_enabled: true
auto_page_title: true
permalink: pretty
mermaid_enabled: true
mermaid_theme: forest
collections:
  root_docs:
    output: true
    directory: .

defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: default
